2022-09-11 14:31:33,338 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 User Successfully Login None None
2022-09-11 14:31:55,231 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 14:32:11,642 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 14:35:24,391 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:13:36,486 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ['no such table: editorial_articleactivity']} None
2022-09-11 15:13:36,491 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ['no such table: editorial_articleactivity']} None
2022-09-11 15:20:59,909 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:22:58,530 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:25:28,551 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:25:54,464 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:25:57,501 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:28:22,507 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:29:10,859 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:30:07,159 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:32:43,362 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article'."]} None
2022-09-11 15:32:43,367 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article'."]} None
2022-09-11 15:43:37,089 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:44:29,581 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article'."]} None
2022-09-11 15:44:29,584 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article'."]} None
2022-09-11 15:46:30,334 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article_instance` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article_instance'."]} None
2022-09-11 15:46:30,339 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article_instance` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article_instance'."]} None
2022-09-11 15:47:16,457 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:47:39,712 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article_instance` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article_instance'."]} None
2022-09-11 15:47:39,715 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["Got AttributeError when attempting to get a value for field `article_instance` on serializer `ArticleActivitySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.\nOriginal exception text was: 'QuerySet' object has no attribute 'article_instance'."]} None
2022-09-11 15:49:11,478 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 15:57:12,035 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 User Successfully Login None None
2022-09-11 15:57:46,765 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["Cannot resolve keyword 'author_details' into field. Choices are: article_instance, article_instance_id, created_at, id, is_admin_approved, is_editor_approved, is_reviewer_approved, updated_at"]} None
2022-09-11 15:57:46,769 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["Cannot resolve keyword 'author_details' into field. Choices are: article_instance, article_instance_id, created_at, id, is_admin_approved, is_editor_approved, is_reviewer_approved, updated_at"]} None
2022-09-11 16:00:25,522 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 16:00:32,046 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Ok None None
2022-09-11 16:06:38,632 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 User Successfully Login None None
2022-09-11 16:07:16,320 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:07:16,324 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:09:20,848 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:09:20,852 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:10:12,396 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:10:12,403 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:11:58,392 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ['Serializers with many=True do not support multiple update by default, only multiple create. For updates it is unclear how to deal with insertions and deletions. If you need to support multiple update, use a `ListSerializer` class and override `.update()` so you can specify the behavior exactly.']} None
2022-09-11 16:11:58,397 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ['Serializers with many=True do not support multiple update by default, only multiple create. For updates it is unclear how to deal with insertions and deletions. If you need to support multiple update, use a `ListSerializer` class and override `.update()` so you can specify the behavior exactly.']} None
2022-09-11 16:16:05,680 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:16:05,687 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:26:57,316 ERROR rest_utils.py:build_response:57  Response: 400 Failed {'article_instance': [ErrorDetail(string='Invalid pk "2" - object does not exist.', code='does_not_exist')]} None
2022-09-11 16:26:57,319 DEBUG rest_utils.py:build_response:71  Response: 200 OK 400 Failed {'article_instance': [ErrorDetail(string='Invalid pk "2" - object does not exist.', code='does_not_exist')]} None
2022-09-11 16:28:30,903 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:28:30,907 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:30:04,267 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:30:04,272 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:32:44,717 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:32:44,720 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:33:11,857 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 User Successfully Login None None
2022-09-11 16:33:59,159 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:33:59,161 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute 'pk'"]} None
2022-09-11 16:35:16,846 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 User Successfully Login None None
2022-09-11 16:35:59,543 ERROR rest_utils.py:build_response:57  Response: 204 Article Successfully Deleted {'non_field_errors': ['Article Successfully Deleted']} None
2022-09-11 16:35:59,545 DEBUG rest_utils.py:build_response:71  Response: 200 OK 204 Article Successfully Deleted {'non_field_errors': ['Article Successfully Deleted']} None
2022-09-11 17:38:44,626 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute '_meta'"]} None
2022-09-11 17:38:44,628 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["'QuerySet' object has no attribute '_meta'"]} None
2022-09-11 17:39:17,457 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 17:42:10,827 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 17:48:43,071 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article_name'` on field 'Field' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:48:43,074 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article_name'` on field 'Field' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:49:13,029 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 17:51:58,155 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ['Field.to_representation() must be implemented for field article_name.']} None
2022-09-11 17:51:58,158 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ['Field.to_representation() must be implemented for field article_name.']} None
2022-09-11 17:52:22,694 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article_name'` on field 'Field' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:52:22,699 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article_name'` on field 'Field' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:53:45,472 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 17:55:22,422 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article'` on field 'RelatedField' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:55:22,425 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article'` on field 'RelatedField' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:55:36,265 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ['RelatedField.to_representation() must be implemented for field article.']} None
2022-09-11 17:55:36,269 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ['RelatedField.to_representation() must be implemented for field article.']} None
2022-09-11 17:56:46,815 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article'` on field 'CharField' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:56:46,818 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["It is redundant to specify `source='article'` on field 'CharField' in serializer 'ArticleActivitySerializer', because it is the same as the field name. Remove the `source` keyword argument."]} None
2022-09-11 17:58:26,999 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ["`HyperlinkedIdentityField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer."]} None
2022-09-11 17:58:27,002 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ["`HyperlinkedIdentityField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer."]} None
2022-09-11 17:58:48,557 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 17:59:48,521 ERROR rest_utils.py:build_response:57  Response: 500 Internal server error {'non_field_errors': ['RelatedField.to_representation() must be implemented for field article_data.']} None
2022-09-11 17:59:48,523 DEBUG rest_utils.py:build_response:71  Response: 200 OK 500 Internal server error {'non_field_errors': ['RelatedField.to_representation() must be implemented for field article_data.']} None
2022-09-11 18:01:48,813 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 18:04:40,336 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 20:30:19,033 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 20:30:32,873 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 20:30:42,285 DEBUG rest_utils.py:build_response:71  Response: 200 OK 200 Article Activity Successfully Updated None None
2022-09-11 20:31:00,117 ERROR rest_utils.py:build_response:57  Response: 400 Failed {'article': [ErrorDetail(string='This field is required.', code='required')]} None
2022-09-11 20:31:00,118 DEBUG rest_utils.py:build_response:71  Response: 200 OK 400 Failed {'article': [ErrorDetail(string='This field is required.', code='required')]} None
